version: '3.1'
services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    volumes:
      - MD:/var/lib/mysql
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      ConNet:
        ipv4_address: 10.10.10.4
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - WP:/var/www/html
    ports:
      - 9000:9000
    env_file:
      - .env
    networks:
      ConNet:
        ipv4_address: 10.10.10.3
  nginx:
    build: ./requirements/nginx
    depends_on:
      - wordpress
      - redis
    volumes:
      - WP:/var/www/html
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    env_file:
      - .env
    networks:
      ConNet:
        ipv4_address: 10.10.10.2
  page:
    build: ./requirements/bonus/page
    container_name: page
    image: page
    ports:
      - 360:360
    env_file:
      - .env
    networks:
      ConNet:
        ipv4_address: 10.10.10.9
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    image: redis
    volumes:
      - RDS:/var/lib/redis
    ports:
      - 6379:6379
    env_file:
      - .env
    networks:
      ConNet:
        ipv4_address: 10.10.10.5
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      ConNet:
        ipv4_address: 10.10.10.6
  vsftpd:
    build: ./requirements/bonus/vsftpd
    container_name: vsftpd
    image: vsftpd
    ports:
      - 20:20
      - 21:21
    volumes:
      - WP:/home/$FTPUSER
    env_file:
      - .env
    networks:
      ConNet:
        ipv4_address: 10.10.10.7
  rsync:
    build: ./requirements/bonus/rsync
    container_name: rsync
    image: rsync
    ports:
      - 600:600
    volumes:
      - WP:/var/wordpress
    env_file:
      - .env
    networks:
      ConNet:
        ipv4_address: 10.10.10.11
networks:
  ConNet:
    driver: bridge
    ipam:
     config:
       - subnet: 10.10.10.0/16
         gateway: 10.10.10.1
volumes:
  WP:
    driver_opts:
      type: none
      o: bind
      device: /home/ychahbi/data/WP
  MD:
    driver_opts:
      type: none
      o: bind
      device: /home/ychahbi/data/MD
  RDS:
    driver_opts:
      type: none
      o: bind
      device: /home/ychahbi/data/RDS