version: '3.1'
services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    image: mariadb
    volumes:
      - /var/Data/MD:/var/www/html
    ports:
      - 3306:3306
    env_file:
      - .env
    networks:
      - ConNet
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    image: wordpress
    depends_on:
      - mariadb
    volumes:
      - /var/Data/WP:/var/www/html
    ports:
      - 9000:9000
    env_file:
      - .env
    networks:
      - ConNet
  nginx:
    build: ./requirements/nginx
    depends_on:
      - wordpress
      - redis
    volumes:
      - /var/Data/WP:/var/www/html
    container_name: nginx
    image: nginx
    ports:
      - 443:443
    env_file:
      - .env
    networks:
      - ConNet
  redis:
    build: ./requirements/bonus/redis
    container_name: redis
    image: redis
    volumes:
      - /var/Data/RDS:/var/lib/redis
    ports:
      - 6379:6379
    env_file:
      - .env
    networks:
      - ConNet
  adminer:
    build: ./requirements/bonus/adminer
    container_name: adminer
    image: adminer
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - ConNet
  vsftpd:
    build: ./requirements/bonus/vsftpd
    container_name: vsftpd
    image: vsftpd
    ports:
      - 20:20
      - 21:21
    volumes:
      - /var/Data/WP:/var/www/html
    env_file:
      - .env
    networks:
      - ConNet
networks:
  ConNet:
